export const config = {
  SERVER_ENDPOINT: process.env.REACT_APP_SERVER_ENDPOINT,
  GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
  GOOGLE_OAUTH_REDIRECT_URL: process.env.REACT_APP_GOOGLE_OAUTH_REDIRECT_URL,
};
